[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_pgsql", "php84Extensions.pcntl", "php84Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "sh start.sh"
